### ISSUE TITLE
Dosages of UKBB individuals

### ISSUE THREAD

**Issue by FedeSantonastaso95** [davidebolo1993/prs_pipeline#1]
Hi Davide,
could you please fix the PRS script to include dosages for all UKBB individuals in the PRS calculation?

Thank you!

**Comment by davidebolo1993** [comment]
You can now run the pipeline in parallel - one chromosome each node. Will provide also a way to merge results downstream.

Best,

Davide

**Comment by davidebolo1993** [comment]
Done also with the other part
